### ISSUE TITLE
New tool uploaded please test and push to the image repositary 

### ISSUE THREAD

**Issue by The-D-lab** [chaimeleon-eu/workstation-images#3]
Hi ,

Please test the new image ([image_batch_shap_explainability_radiomics](https://github.com/chaimeleon-eu/image_batch_shap_explainability_radiomics)) that we have uploaded .

regards,
D-Lab,
UM

**Comment by Palollo** [comment]
There are few required changes: 
 - Please remove spaces from the LABEL version in dockerfile.
 - Repository is public but it has no license. Please [add one](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) or the LABEL `authorization` (see [Labels](https://github.com/chaimeleon-eu/workstation-images#labels) section).

Other recommendations:
  - Doing `COPY ./ ./` without a `.dockerignore` file is not the best practice, because all the files will be copied to the root directory `/` in the image, including unwanted `.git/`, `Dockerfile`, etc. It is better to create a subdirectory (for example named "app"), move your files (main.py, tab_shap.py, examples, etc.) to it and copy only that. Example:
    ```
    RUN mkdir /app
    COPY ./app README.md LICENSE /app/
    ```

**Comment by Palollo** [comment]
Another thing...
I see `main.py` does not accept arguments, just reads a `config.ini` file, so at least this file should be read from `/home/chaimeleon/persistent-home/shap-explainability-radiomics/config.ini`. The persistent-home is the directory mounted on the container where the user can write (edit the configuration she/he wants). So this way usually the user will set the first lines in this file like this:
```
model_filename = /home/chaimeleon/persistent-home/shap-explainability-radiomics/test_model.sav
test_data_preprocess = /home/chaimeleon/persistent-home/shap-explainability-radiomics/test_file.npy
save_dir_for_plots = /home/chaimeleon/persistent-home/shap-explainability-radiomics/test_run
```

Anyway, as soon as you make the required changes I told you in my previous message, then we will build and upload the image to the CHAIMELEON repository, so you will be able to test and see all this things and adjust them ;)

**Comment by Palollo** [comment]
Ok, I see you added a license yesterday. The testing version of the image has been uploaded. 
If you create a desktop workstation in the platform you will be able to see your image with the command: `jobman images`
Also you will see the details with: `jobman image-details -i sharp-exp-tool`
And you can launch a job using this image with: `jobman submit -i sharp-exp-tool:0.0.1-testing`

It is recommended to add some usage example like the previous in the `README.md`, see [this](https://github.com/chaimeleon-eu/workstation-images#usage-examples).

And the log for the job lauched currently is like this:
```
----Log begin----

  python: can't open file '/workspace/main.py': [Errno 2] No such file or directory
  
----Log end----
```

I close the issue for now. Feel free to reopen or create a new one when you fix the issues and you have a new version ;)
