### ISSUE TITLE
error regarding image_batch_shap_explainability_radiomics

### ISSUE THREAD

**Issue by The-D-lab** [chaimeleon-eu/workstation-images#4]
Hi ,

When I tried to run the job on ([image_batch_shap_explainability_radiomics](https://github.com/chaimeleon-eu/image_batch_shap_explainability_radiomics)) i get teh following error on console ,

![image](https://github.com/chaimeleon-eu/workstation-images/assets/54101202/1cc52270-ca56-4540-9ce4-89874b193e2e)

Furthermore , regarding the following  error you mentioned in the previous [issue](https://github.com/chaimeleon-eu/workstation-images/issues/3#issuecomment-1680559340). I'm not sure how to solve this on the docker file as I have followed the same standard in other repositories.  
----Log begin----

  python: can't open file '/workspace/main.py': [Errno 2] No such file or directory
  
----Log end----

It would be great if you can help to sort this out.

Thank You

**Comment by Palollo** [comment]
That error message appear when there is not dataset selected to work with when the workstation is created. It is already notified in the jobman project: https://github.com/chaimeleon-eu/jobman/issues/29

**Comment by Palollo** [comment]
Regarding the error "python: can't open file '/workspace/main.py'"...
If you build your image locally and run, you will see that the file `main.py` is in the root directory `/`, and not in `/workspace/`.
You can remove `workspace/` in the entrypoint of [your dockerfile](https://github.com/chaimeleon-eu/image_batch_shap_explainability_radiomics/blob/main/Dockerfile#L33),
or see [my recommendation](https://github.com/chaimeleon-eu/workstation-images/issues/3#issuecomment-1677805405) in the previous issue and move your app files to a new directory (named `workspace` in this case instead of `app`).

**Comment by The-D-lab** [comment]
Hi , 
We have fixed the  requested changes/recommendations , please build and upload the image.

Thank you

**Comment by Palollo** [comment]
The docker image has been rebuilt with tags '0.0.2-testing' and 'latest':
![imagen](https://github.com/chaimeleon-eu/workstation-images/assets/10077592/f760fc31-1d96-4627-b6a8-15d00b3c21e1)

Also the issue https://github.com/chaimeleon-eu/jobman/issues/29 was fixed.
