### ISSUE TITLE
BUg fix in image_batch_shap_explainability_radiomics

### ISSUE THREAD

**Issue by The-D-lab** [chaimeleon-eu/workstation-images#5]
We have fixed a bug in [image_batch_shap_explainability_radiomics](https://github.com/chaimeleon-eu/image_batch_shap_explainability_radiomics) can you pleae update the docker image in the platform ? 

You can find the changes [here](https://github.com/chaimeleon-eu/image_batch_shap_explainability_radiomics/commit/a6a36c6e635e719baef359ad148315cdb3cef47d)

new version is ="0.0.3 - testing"

**Comment by Palollo** [comment]
OK, docker image updated in the platform: new version added "0.0.3-testing" (please avoid spaces in the version and correct also the label "name", the value currently is "sharp-...", but I suppose it should be "shap-...").
Also I copied the example files (`config.ini`, `test_model.sav`, `test_file.npy`) in the persistent-shared-folder, so the user can copy directly from there instead of upload.
I've done a small test and it seems working.
Basically what I've done in a new desktop-tensorflow:
```bash
cd
mkdir persistent-home/shap-explainability-radiomics
cd persistent-home/shap-explainability-radiomics
cp ~/persistent-shared-folder/apps/shap-explainability-radiomics/* .
jobman submit -i shap-exp-tool -- ~/persistent-home/shap-explainability-radiomics/config.ini
# according to the config.ini file, the results are written in test_run
ls test_run
```
You should update the usage section in README.md for guiding user to use the persistent-home and how to launch correctly (you can take the commands of my test).
