### ISSUE TITLE
Update batch tool

### ISSUE THREAD

**Issue by Nandayang** [chaimeleon-eu/workstation-images#6]
I would like to update our harmonization tools and have uploaded the v2.0 version to 
https://github.com/chaimeleon-eu/image_batch_lungCT_harmonisation/tree/main/V2.
Could you please integrate it into the platform? Many thanks.

**Comment by Palollo** [comment]
Does V2 replace the previous version?

**Comment by Nandayang** [comment]
> Does V2 replace the previous version?

Yes, it could replace the previous version

**Comment by Palollo** [comment]
17.2GB of image size!

Could you use the "runtime" version for the base image instead of the "devel"?
`FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel`  --> `FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime`
If possible it would be a good point to reduce the size to something more affordable.

Also it would be useful you check the [recommendations in the guide](https://github.com/chaimeleon-eu/workstation-images/blob/main/README.md#recommendations-for-reducing-the-image-size).
In that way you can change that:
```
RUN apt-get update
RUN pip install numpy
RUN pip install SimpleITK
RUN pip install tqdm
RUN pip install scipy
```
Into that:
```
RUN pip install --no-cache-dir  numpy SimpleITK tqdm scipy
```
So if you agree and apply these changes, the image size finally would reduce to 7.66GB

**Comment by Nandayang** [comment]
@Palollo Yes for sure, I've tested and everything works fine with the 'runtime' version.

**Comment by Palollo** [comment]
Great, so it is already uploaded as:
harmonisation-lungct:2.0
harmonisation-lungct:latest

**Comment by Nandayang** [comment]
@Palollo Another issue is that when I try to launch an application to test my batch tool, it always shows 'Not Ready 0 Pod', and I cannot access the remote service (I've tried both desktop-pytorch and jupyter pytorch).

**Comment by Palollo** [comment]
This is something that can happen when there are not enough resources in that moment, because there are other desktops created by other users. 
Just a reminder: it is important to release (delete) the desktop when the work is finished to let the resources available to other users.
Anyway I can say currently there are resouces available to your desktop, it should work if you try to launch ;)

**Comment by Nandayang** [comment]
@Palollo Thanks for your help and it works now. Btw, I made some modifications to the script and could you please help me to update it on the platform? The path is still in https://github.com/chaimeleon-eu/image_batch_lungCT_harmonisation/tree/main/V2 
Many thanks

**Comment by Palollo** [comment]
OK, it's now updated on the platform as:
> harmonisation-lungct:2.1
> harmonisation-lungct:latest

You should update the dockerfile accordingly:
```
LABEL name="harmonisation-lungct"
LABEL version="2.1"
```
